### ISSUE TITLE
error in "prepare_annotation_files"

### ISSUE THREAD

**Issue by Leo-ccc** [hsinyenwu/RiboseQC_R4.2.1#1]
Hi!
Thanks for your updates!

I am using R4.1, and when I run 
`prepare_annotation_files(annotation_directory = "RiboseQC_annotation",twobit_file = "my.2bit",gtf_file = "my.gtf",scientific_name = "Amphidinium.carterae",annotation_name = "Amphidinium_carterae" ,export_bed_tables_TxDb = F,forge_BSgenome = T,create_TxDb = T)`

It stopped by 
```
Error in .make_Seqinfo_from_genome(genome) : 
  "Amphidiniumcarterae" is not a registered NCBI
  assembly or UCSC genome (use
  registered_NCBI_assemblies() or
  registered_UCSC_genomes() to list the NCBI or UCSC
  assemblies/genomes currently registered in the
  GenomeInfoDb package)
In addition: Warning messages:
1: In forgeBSgenomeDataPkg(y, seqs_srcdir = seqs_srcdir, destdir = destdir,  :
  field 'provider_version' is deprecated in favor of 'genome'
2: In forgeBSgenomeDataPkg(y, seqs_srcdir = seqs_srcdir, destdir = destdir,  :
  field 'release_name' is deprecated
```

My genome reference was assembled  by our lab , so it is not registered in BSgenomoDB.
I think this error suggests that the "seed" file need information of "Seqnames = " and the function misses it.

Do you know how to fix it?

Thank you !!

**Comment by hsinyenwu** [comment]
Hi Leo,
This is related to the BSgenome package: https://github.com/Bioconductor/BSgenome/issues/18
I think you need to add your organism to GenomeInfoDb and also update a file in the BSgenome package. Check out the [BSgenomeForge vignette](https://bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf). 

But I have not tried that before. Good luck!

**Comment by Leo-ccc** [comment]
Thank you for your reply!
I followed your advices and made some modifications in **riboseqc.R**

1. Replaced :
`      circseed<-circss
        if(length(circseed)==0){circseed<-NULL}`
to
`      circseed<-circss
        if(length(circseed)==0){circseed<-character(0)}`

2. Replaced :
`     if(length(circseed)==0){
            writeLines(text = seed_text,con = seed_dest)
        }`
to
`     if(length(circseed)==0){
          seed_text<-paste(seed_text,"\n",
                           "circ_seqs: ",character(0),sep="")
        }`

Now it worked for any given reference (I think...)

Thanks again and wish you all the best.
